version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DO_TOKEN: ${DO_NONADMIN}
    expose:
      - "3000"
